add insights_columns(amV2 field for Insights API endpoints on 2024-08…
maiha/smartnews.cr pull request #10
Opened 2024-08-26 08:40 UTC by norihito-sato-ss

…-01)

2024-08-28 02:52 UTC, maiha requested changes
めっちゃ多いカラム追加、ご苦労さまです。ありがとうございます！

今回からamv2の参照が楽にできるようになったので、そこの変更をお願いします。
❌従来: campaign.amv2で取得したデータをinsightから無理やりhash経由で利用
✅今回: insight.amv2をそのまま利用

前回の私がやった「従来」の部分は黒歴史ということで、全部削除しちゃって下さい 🙇

2024-08-28 02:52 UTC, maiha commented on src/cli/cmds/batch/tsv.cr
46～51行目の amv2_hash は全部削ってよさそう
1. 以前は insight.amv2 に値が入ってなかった
2. campaign.amv2 には値が入っており、むりくり1のように使えるhashを作っていた(ここの部分)
3. 今回から1で自然に参照できるようになった

2024-08-28 02:52 UTC, maiha commented on src/cli/cmds/batch/tsv.cr
>            amv2 = amv2_hash[insight.campaign_id.to_s]? || Smartnews::Proto::Amv2.new
同様に、ここの amv2 は「campaign経由のむりくり参照」なので、消してOK
PRで追加してもらったこの後の `insight_amv2` も一緒に消してOK
今回insight→amv2を直接参照できるようになったので、以下のようにシンプルにできるはず

```suggestion
          amv2 = insight.amv2 || Smartnews::Proto::Amv2.new
```

2024-08-28 02:52 UTC, maiha commented on src/cli/cmds/batch/tsv.cr
> +              if insight_amv2[_key]
ここの insight_amv2 も直前の行の amv2 への参照に集約されたので、削除してOKです

2024-08-28 02:52 UTC, maiha commented on proto/smartnews/report.proto
> +  // insight.amV2
本質的じゃないコメントの部分になります。
少し上の
```
  // campaign.amV2
```

を `insight.amV2` に変更しちゃって下さい。

2024-08-28 04:26 UTC, norihito-sato-ss commented on proto/smartnews/report.proto
> +  // insight.amV2
承知しました。🙇‍♂️

2024-08-28 04:27 UTC, norihito-sato-ss commented on src/cli/cmds/batch/tsv.cr
> +              if insight_amv2[_key]
承知しました。🙇‍♂️

2024-08-28 04:27 UTC, norihito-sato-ss commented on src/cli/cmds/batch/tsv.cr
>            amv2 = amv2_hash[insight.campaign_id.to_s]? || Smartnews::Proto::Amv2.new
なるほど。ありがとうございます。承知しました。🙇‍♂️

2024-08-28 04:28 UTC, norihito-sato-ss commented on src/cli/cmds/batch/tsv.cr
なるほど。ありがとうございます。承知しました。🙇‍♂️

2024-08-28 09:22 UTC, norihito-sato-ss commented
amv2_campaign_spending_limit,amv2_campaign_daily_budget が insights のエンドポイントから値が取得できないため、campaign の amV2 の処理は残しておきます。🙇‍♂️
(取得はできないですが、すぐに対応可能できるようにするため)

2024-08-29 02:39 UTC, maiha commented
> amv2_campaign_spending_limit,amv2_campaign_daily_budget が insights のエンドポイントから値が取得できない

あ、勘違いしてました。「campaign.amv2」と「insight.amv2」は同じものだと思い込んでました。
campaignにしかない情報があるんですね。ご指摘通り、残す必要がありますね。

ということは、
* `amv2_hash` ← 消してもらったけど、やっぱり必要だから復活？
* そもそも amv2 の内容が別なら `Proto::Amv2` も正しくなくて、 `Proto::Campaign::Amv2` と Insight に分ける？

2024-08-29 03:03 UTC, maiha commented
私がレビューして修正依頼をする前の、「最初のPR状態」がほぼほぼ正しい気がしてきました。
* `amv2_hash` : 消したけど戻す。名前がややこいので、 `campaign_amv2_hash` にする
* (tsv作成ループ中の) `amv2` : PR前の campaign 専用に戻す。名前は `campaign_amv2` にする
* `insight_amv2` : 同様にinsight版も作る。 `insight.amv2 || (proto.new)` 的な。ほぼamv2の参照と同じだけどNull Objectパターンにしておきたいやつ
* (keys.each のループ中) `campaign_amv2` と `insight_amv2` の両方から引く

2024-08-29 03:42 UTC, norihito-sato-ss commented
ご連絡ありがとうございます。現在気になっていたことをまとめていただき非常に助かりました。🙇‍♂️
smartnews の api の v2 がもうすぐ出るのであれば、`Proto::Campaign::Amv2`と`Proto::Insight::Amv2`の対応は今回は見送れればと考えております。現在使っている api で次回 amv2 の追加カラム対応の依頼があればその際に対応したいと思います。

2024-08-29 05:31 UTC, maiha approved these changes
対応ありがとうございます！

2024-08-29 05:31 UTC, maiha commented on src/cli/cmds/batch/tsv.cr
> +          insight_amv2 = insight.amv2 || Smartnews::Proto::Amv2.new
おお、2つのamv2肉付けデータが対象的で理解しやすい。これだった 👍

2024-08-29 05:31 UTC, maiha commented on src/cli/cmds/batch/tsv.cr
> +              end
細かいですが。最適化目的ではなくて、「campagin→insightの順で参照」の意図が伝わりやすくなるので。

```suggestion
              _val = campaign_amv2[_key]? || insight_amv2[_key]?
```

2024-08-29 06:32 UTC, norihito-sato-ss commented on src/cli/cmds/batch/tsv.cr
> +              end
ありがとうございます。修正します。🙇‍♂️

2024-08-29 08:28 UTC, merged

2024-08-29 08:28 UTC, maiha commented
ありがとうございます！